import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

export const metadata = {
  title: "Privacy Policy",
};

export default function PolicyPage() {
  return (
    <div className="min-h-screen bg-slate-50 text-slate-900">
      <Navbar />

      <section className="bg-[#1E0306] text-white py-16 px-4 md:px-8 text-center">
        <div className="mx-auto max-w-3xl space-y-2">
          <h1 className="text-3xl md:text-5xl font-black">
            Privacy <span className="text-[#ED3C52]">Policy</span>
          </h1>
          <p className="text-xs text-rose-200/70">Last updated: August 2026</p>
        </div>
      </section>

      <main className="mx-auto max-w-3xl px-4 py-16 space-y-8 text-sm text-slate-600 leading-relaxed">
        <div className="rounded-2xl bg-white p-8 border border-slate-200 shadow-sm space-y-7">
          <section className="space-y-2">
            <h2 className="text-base font-bold text-[#1E0306]">1. Introduction</h2>
            <p>Prince of Forex (PFX Academy) ("we", "us", or "our") is committed to protecting your personal information. This Privacy Policy explains how we collect, use, and safeguard the data you provide when interacting with our website or purchasing our courses.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-[#1E0306]">2. Information We Collect</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>Email Address</strong> — collected at checkout to deliver course materials and send order receipts.</li>
              <li><strong>Transaction Reference</strong> — generated by Paystack to track your purchase.</li>
              <li><strong>Newsletter Subscription</strong> — your email, only if you explicitly opt in to receive PFX market updates.</li>
              <li><strong>Usage Data</strong> — basic server-side logs (page visits, API requests) for security and performance monitoring.</li>
            </ul>
            <p>We do <strong>not</strong> collect or store your credit/debit card details. All payment data is handled directly by Paystack's PCI DSS compliant infrastructure.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-[#1E0306]">3. How We Use Your Information</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>To deliver the purchased course materials to your email address.</li>
              <li>To send transaction receipts and order confirmations.</li>
              <li>To send newsletter updates and market tips, if you have subscribed.</li>
              <li>To maintain records of completed transactions for legal and financial compliance.</li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-[#1E0306]">4. Third-Party Services</h2>
            <p>We use the following trusted third-party providers to operate our platform:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>Paystack</strong> — payment processing. Your payment data is governed by Paystack's Privacy Policy.</li>
              <li><strong>Resend</strong> — transactional email delivery. Emails containing course access links are sent via Resend.</li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-[#1E0306]">5. Data Retention</h2>
            <p>We retain your email address and transaction records for a minimum of 3 years for legal, tax, and support purposes. Newsletter subscribers may unsubscribe at any time by clicking the unsubscribe link in any PFX newsletter email.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-[#1E0306]">6. Your Rights</h2>
            <p>You have the right to request access to, correction of, or deletion of any personal data we hold about you. To exercise these rights, contact us directly via the PFX Academy platform.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-[#1E0306]">7. Cookies</h2>
            <p>This website may use essential cookies to maintain functionality. We do not use tracking or advertising cookies. No personal browsing data is sold to third parties.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-[#1E0306]">8. Changes to this Policy</h2>
            <p>We reserve the right to update this Privacy Policy at any time. Continued use of the platform after any changes constitutes your acceptance of the revised policy.</p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
